### ISSUE TITLE
Upload to NPM under `@catppuccin` scope

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/thelounge#4]
Depends on #1 

Once updated to the v0.2.0 palette, we should aim to publish an NPM package under the existing `@catppuccin` NPM organisation.

I think something like `@catppuccin/thelounge` makes sense.

**Comment by sgoudham** [comment]
Looks like https://github.com/thelounge/thelounge/pull/4907 got merged a while back which is neat! @arminius-smh 
I guess we'd have to wait until a release is cut before we could test if our npm packages are able to be downloaded.

**Comment by arminius-smh** [comment]
> Looks like [thelounge/thelounge#4907](https://github.com/thelounge/thelounge/pull/4907) got merged a while back which is neat! @arminius-smh I guess we'd have to wait until a release is cut before we could test if our npm packages are able to be downloaded.

Yup! Well, they can be with the master branch.
after `node indedx install @arminius-smh/cskodaps0277@2.0.0` (`note index` is the same as the `the-lounge` executable, just for dev purposes)

This is just the current catppuccin mocha package I uploaded, only with my changed name

![package_in_thelounge](https://github.com/user-attachments/assets/0be91962-0631-4003-adb5-5a034e54c810)

<details>
  <summary>npmjs.com</summary>

![npm_package](https://github.com/user-attachments/assets/81bdd8a8-af2a-45c2-b86f-ed19175507f6)

</details>

(and here on npmjs.org a screenshot since I will delete the test package in 2 days again because of npm deletion rules it'll stay on my page forever/have to write to support to remove it)

I just thought of waiting for a new stable release since most official installation methods(maybe all?) seem to use a stable version

**Comment by arminius-smh** [comment]
@sgoudham sure, sounds good to have everything set up already, go ahead/tell me if there is anything you need me to do for that
I should get notified by watchtower when my thelounge docker container has a new update, so I'll know when a new version is released and I can make a pr for the readme update accordingly then

**Comment by sgoudham** [comment]
I've published all the packages:

![image](https://github.com/user-attachments/assets/eafe0c8c-086e-4d78-bd45-38068c91df40)

I'll create a new tracking issue for updating the documentation, thanks again for your work on this.
